config/routes.rb
Rails.application.routes.draw do
  post 'search/results'

  get 'static_pages/about'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/privacy'

  devise_for :users, controllers: { registrations: "users/registrations" }

  root 'static_pages#home'

  resources :mechanics
  resources :keywords, only: [:show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = "en">
  <head>
    <title>Game Mechanics Wiki</title>
  <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- setup mobile responsive aspects -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"> -->


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  </head>
  <body>

	      
	      <div class = "sidebar">
	        <%= link_to "Home", root_path%>
	        <br>
            <%= form_tag search_results_url do %>

            <p>
              <%= text_field_tag :search, params[:search] %>
              <%= submit_tag "Search", :name => nil %>
            </p>
          <% end %>
	      </div>
	      
	      
	      <div class = "main">
	      	<%= yield %>
       
	      </div>


    
  </body>
</html>